---
name: Check ğŸ› 

on:
  push:
    branches:
      - wasm-poc

jobs:
  build-wasm:
    name: Build WASM ğŸ§‘â€ğŸ­
    needs: release
    uses: insightsengineering/r.pkg.template/.github/workflows/wasm.yaml@wasm-poc
