---
name: Release ðŸŽˆ

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  docs:
    name: Pkgdown Docs ðŸ“š
    needs: release
    uses: insightsengineering/r.pkg.template/.github/workflows/pkgdown.yaml@non-cran-unit-test-report
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      default-landing-page: latest-tag
      additional-unit-test-report-directories: unit-test-report-non-cran
  release:
    name: Create release ðŸŽ‰
    uses: insightsengineering/r.pkg.template/.github/workflows/release.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  build:
    name: Build package and reports ðŸŽ
    needs: [release, docs]
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@non-cran-unit-test-report
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        _R_CHECK_CRAN_INCOMING_REMOTE_=false
      additional-r-cmd-check-params: --as-cran
      enforce-note-blocklist: true
      note-blocklist: |
        checking dependencies in R code .* NOTE
        checking R code for possible problems .* NOTE
        checking examples .* NOTE
        checking Rd line widths .* NOTE
        checking top-level files .* NOTE
      unit-test-report-brand: >-
        https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/thumbs/tern.png
  r-cmd-non-cran:
    name: Build package and reports (non-CRAN) ðŸ§¬
    needs: [release, docs]
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@non-cran-unit-test-report
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        _R_CHECK_CRAN_INCOMING_REMOTE_=false
      enforce-note-blocklist: true
      note-blocklist: |
        checking dependencies in R code .* NOTE
        checking R code for possible problems .* NOTE
        checking examples .* NOTE
        checking Rd line widths .* NOTE
        checking top-level files .* NOTE
      unit-test-report-brand: >-
        https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/thumbs/tern.png
      unit-test-report-directory: unit-test-report-non-cran
      concurrency-group: non-cran
  coverage:
    name: Coverage ðŸ“”
    needs: [release, docs]
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@non-cran-unit-test-report
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
